// <auto-generated />
using AWD1115Final.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AWD1115Final.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AWD1115Final.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("AssignedMechanic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CompletionTime")
                        .HasColumnType("real");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            AssignedMechanic = "",
                            CompletionTime = 0.5f,
                            CustomerName = "",
                            Description = "Change oil and oil filter",
                            IsCompleted = true,
                            Name = "Oil Change",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 2,
                            AssignedMechanic = "",
                            CompletionTime = 1f,
                            CustomerName = "",
                            Description = "Replace Break Pads",
                            IsCompleted = true,
                            Name = "Breaks",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 3,
                            AssignedMechanic = "",
                            CompletionTime = 0.25f,
                            CustomerName = "",
                            Description = "Replace Air Filter",
                            IsCompleted = true,
                            Name = "Air Filter",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 4,
                            AssignedMechanic = "",
                            CompletionTime = 0.25f,
                            CustomerName = "",
                            Description = "Replace Cabin Filter",
                            IsCompleted = true,
                            Name = "Cabin Filter",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 5,
                            AssignedMechanic = "",
                            CompletionTime = 2f,
                            CustomerName = "",
                            Description = "Balance And Install/Mount New Tires",
                            IsCompleted = true,
                            Name = "Tire Mounting And Balancing",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 6,
                            AssignedMechanic = "",
                            CompletionTime = 0.1f,
                            CustomerName = "",
                            Description = "Replace Windshield Wipers",
                            IsCompleted = true,
                            Name = "Windshield Wipers",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 7,
                            AssignedMechanic = "",
                            CompletionTime = 1f,
                            CustomerName = "",
                            Description = "Rotate Tires",
                            IsCompleted = true,
                            Name = "Tire Rotation",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 8,
                            AssignedMechanic = "",
                            CompletionTime = 0.5f,
                            CustomerName = "",
                            Description = "Remove/Drain And Replace Vehicle's Fluids",
                            IsCompleted = true,
                            Name = "Change Fluids",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 9,
                            AssignedMechanic = "",
                            CompletionTime = 0.5f,
                            CustomerName = "",
                            Description = "Replace Catalitic Convertor",
                            IsCompleted = true,
                            Name = "Catalitic Convertor",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 10,
                            AssignedMechanic = "",
                            CompletionTime = 0.25f,
                            CustomerName = "",
                            Description = "Replace Of Spark Plugs",
                            IsCompleted = true,
                            Name = "Spark Plugs",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 11,
                            AssignedMechanic = "",
                            CompletionTime = 10f,
                            CustomerName = "",
                            Description = "Replace Head Gasket",
                            IsCompleted = true,
                            Name = "Internal Engine Work",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 12,
                            AssignedMechanic = "",
                            CompletionTime = 0.25f,
                            CustomerName = "",
                            Description = "Replace Water Pump",
                            IsCompleted = true,
                            Name = "Water Pump",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 13,
                            AssignedMechanic = "",
                            CompletionTime = 0.25f,
                            CustomerName = "",
                            Description = "Replace Alternator",
                            IsCompleted = true,
                            Name = "Alternator",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 14,
                            AssignedMechanic = "",
                            CompletionTime = 0.5f,
                            CustomerName = "",
                            Description = "Replace Intake",
                            IsCompleted = true,
                            Name = "Intake",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 15,
                            AssignedMechanic = "",
                            CompletionTime = 1f,
                            CustomerName = "",
                            Description = "Replace Exhaust Manifold",
                            IsCompleted = true,
                            Name = "Exhaust Manifold",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 16,
                            AssignedMechanic = "",
                            CompletionTime = 6f,
                            CustomerName = "",
                            Description = "Replace Clutch",
                            IsCompleted = true,
                            Name = "Clutch",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 17,
                            AssignedMechanic = "",
                            CompletionTime = 5f,
                            CustomerName = "",
                            Description = "Replace Transmission",
                            IsCompleted = true,
                            Name = "Transmission",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 18,
                            AssignedMechanic = "",
                            CompletionTime = 3.25f,
                            CustomerName = "",
                            Description = "Fix Electrical Issues",
                            IsCompleted = true,
                            Name = "Electrical Issues",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 19,
                            AssignedMechanic = "",
                            CompletionTime = 7.75f,
                            CustomerName = "",
                            Description = "Replace Pistons And Rings",
                            IsCompleted = true,
                            Name = "Engine Internals",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 20,
                            AssignedMechanic = "",
                            CompletionTime = 15f,
                            CustomerName = "",
                            Description = "Replace Engine",
                            IsCompleted = true,
                            Name = "Engine Replacement",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 21,
                            AssignedMechanic = "",
                            CompletionTime = 2.5f,
                            CustomerName = "",
                            Description = "Fix Wiring",
                            IsCompleted = true,
                            Name = "Fix Wiring",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 22,
                            AssignedMechanic = "",
                            CompletionTime = 1.5f,
                            CustomerName = "",
                            Description = "Any Work Here",
                            IsCompleted = true,
                            Name = "Work On A Maserati",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 23,
                            AssignedMechanic = "",
                            CompletionTime = 1.5f,
                            CustomerName = "",
                            Description = "Any Work Here",
                            IsCompleted = true,
                            Name = "Work On A Alpha Romeo",
                            Priority = "Low",
                            SkillLevel = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
