// <auto-generated />
using CH06Lab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CH06Lab.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929033932_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CH06Lab.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "setup",
                            Name = "Setup"
                        },
                        new
                        {
                            Id = "usage",
                            Name = "Usage"
                        },
                        new
                        {
                            Id = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("CH06Lab.Models.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FaqId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqId = 1,
                            Answer = "Use <script src=\"...\"></script> before the closing body tag.",
                            CategoryId = "setup",
                            Question = "How do I include a script tag?",
                            TopicId = "js"
                        },
                        new
                        {
                            FaqId = 2,
                            Answer = "let and const have block scope, var is function scoped.",
                            CategoryId = "usage",
                            Question = "What is var vs let?",
                            TopicId = "js"
                        },
                        new
                        {
                            FaqId = 3,
                            Answer = "Use the class keyword and place members inside braces.",
                            CategoryId = "usage",
                            Question = "How do I create a class in C#?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            FaqId = 4,
                            Answer = "HTML was created in 1991 by Tim Berners-Lee.",
                            CategoryId = "hist",
                            Question = "When was HTML created?",
                            TopicId = "html"
                        });
                });

            modelBuilder.Entity("CH06Lab.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "js",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = "csharp",
                            Name = "C#"
                        },
                        new
                        {
                            Id = "html",
                            Name = "HTML"
                        });
                });

            modelBuilder.Entity("CH06Lab.Models.Faq", b =>
                {
                    b.HasOne("CH06Lab.Models.Category", "Category")
                        .WithMany("Faqs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CH06Lab.Models.Topic", "Topic")
                        .WithMany("Faqs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CH06Lab.Models.Category", b =>
                {
                    b.Navigation("Faqs");
                });

            modelBuilder.Entity("CH06Lab.Models.Topic", b =>
                {
                    b.Navigation("Faqs");
                });
#pragma warning restore 612, 618
        }
    }
}
