// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S3FinalV2.Data;

#nullable disable

namespace S3FinalV2.Migrations
{
    [DbContext(typeof(MechTrackDbContext))]
    partial class MechTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("S3FinalV2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("S3FinalV2.Models.AssignedJobs", b =>
                {
                    b.Property<int>("AssignedJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedJobId"));

                    b.Property<float?>("ActualHours")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomersCustomerId")
                        .HasColumnType("int");

                    b.Property<float>("EstimatedHours")
                        .HasColumnType("real");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobsId")
                        .HasColumnType("int");

                    b.Property<int?>("JobsJobId")
                        .HasColumnType("int");

                    b.HasKey("AssignedJobId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomersCustomerId");

                    b.HasIndex("JobsId");

                    b.HasIndex("JobsJobId");

                    b.ToTable("AssignedJobs");
                });

            modelBuilder.Entity("S3FinalV2.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("S3FinalV2.Models.Jobs", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<float>("AvgCompletionTime")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstCompTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            AvgCompletionTime = 0f,
                            Description = "Change oil and oil filter",
                            EstCompTime = "0.5",
                            Name = "Oil Change",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 2,
                            AvgCompletionTime = 0f,
                            Description = "Replace Break Pads",
                            EstCompTime = "1",
                            Name = "Breaks",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 3,
                            AvgCompletionTime = 0f,
                            Description = "Replace Air Filter",
                            EstCompTime = "0.25",
                            Name = "Air Filter",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 4,
                            AvgCompletionTime = 0f,
                            Description = "Replace Cabin Filter",
                            EstCompTime = "0.25",
                            Name = "Cabin Filter",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 5,
                            AvgCompletionTime = 0f,
                            Description = "Balance And Install/Mount New Tires",
                            EstCompTime = "2",
                            Name = "Tire Mounting And Balancing",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 6,
                            AvgCompletionTime = 0f,
                            Description = "Replace Windshield Wipers",
                            EstCompTime = "0.25",
                            Name = "Windshield Wipers",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 7,
                            AvgCompletionTime = 0f,
                            Description = "Rotate Tires",
                            EstCompTime = "1",
                            Name = "Tire Rotation",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 8,
                            AvgCompletionTime = 0f,
                            Description = "Remove/Drain And Replace Vehicle's Fluids",
                            EstCompTime = "0.5",
                            Name = "Change Fluids",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 9,
                            AvgCompletionTime = 0f,
                            Description = "Replace Catalitic Convertor",
                            EstCompTime = "0.5",
                            Name = "Catalitic Convertor",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 10,
                            AvgCompletionTime = 0f,
                            Description = "Replace Of Spark Plugs",
                            EstCompTime = "0.25",
                            Name = "Spark Plugs",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 11,
                            AvgCompletionTime = 0f,
                            Description = "Replace Head Gasket",
                            EstCompTime = "1",
                            Name = "Internal Engine Work",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 12,
                            AvgCompletionTime = 0f,
                            Description = "Replace Water Pump",
                            EstCompTime = "0.25",
                            Name = "Water Pump",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 13,
                            AvgCompletionTime = 0f,
                            Description = "Replace Alternator",
                            EstCompTime = "0.25",
                            Name = "Alternator",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 14,
                            AvgCompletionTime = 0f,
                            Description = "Replace Intake",
                            EstCompTime = "0.5",
                            Name = "Intake",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 15,
                            AvgCompletionTime = 0f,
                            Description = "Replace Exhaust Manifold",
                            EstCompTime = "1",
                            Name = "Exhaust Manifold",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 16,
                            AvgCompletionTime = 0f,
                            Description = "Replace Clutch",
                            EstCompTime = "6",
                            Name = "Clutch",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 17,
                            AvgCompletionTime = 0f,
                            Description = "Replace Transmission",
                            EstCompTime = "5",
                            Name = "Transmission",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 18,
                            AvgCompletionTime = 0f,
                            Description = "Fix Electrical Issues",
                            EstCompTime = "3.25",
                            Name = "Electrical Issues",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 19,
                            AvgCompletionTime = 0f,
                            Description = "Replace Pistons And Rings",
                            EstCompTime = "7.75",
                            Name = "Engine Internals",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 20,
                            AvgCompletionTime = 0f,
                            Description = "Replace Engine",
                            EstCompTime = "15",
                            Name = "Engine Replacement",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 21,
                            AvgCompletionTime = 0f,
                            Description = "Fix Wiring",
                            EstCompTime = "2.5",
                            Name = "Fix Wiring",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 22,
                            AvgCompletionTime = 0f,
                            Description = "Any Work Here",
                            EstCompTime = "1.5",
                            Name = "Work On A Maserati",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 23,
                            AvgCompletionTime = 0f,
                            Description = "Any Work Here",
                            EstCompTime = "1.5",
                            Name = "Work On A Alpha Romeo",
                            Priority = "Low",
                            SkillLevel = 4
                        });
                });

            modelBuilder.Entity("S3FinalV2.Models.MechanicAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ActualHours")
                        .HasColumnType("real");

                    b.Property<float>("AssignedHours")
                        .HasColumnType("real");

                    b.Property<int>("AssignedJobId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedJobId");

                    b.HasIndex("MechanicId");

                    b.ToTable("MechanicAssignments");
                });

            modelBuilder.Entity("S3FinalV2.Models.Mechanics", b =>
                {
                    b.Property<int>("MechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicId"));

                    b.Property<float>("HourlyLimitPerWeek")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<float>("TotalHoursWorked")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MechanicId");

                    b.HasIndex("UserId");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WorkWeeks");
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeekAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedJobId")
                        .HasColumnType("int");

                    b.Property<int>("WorkWeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedJobId");

                    b.HasIndex("WorkWeekId");

                    b.ToTable("WorkWeekAssignments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S3FinalV2.Models.ApplicationUser", b =>
                {
                    b.HasOne("S3FinalV2.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("S3FinalV2.Models.Mechanics", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId");

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("S3FinalV2.Models.AssignedJobs", b =>
                {
                    b.HasOne("S3FinalV2.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.Customers", null)
                        .WithMany("AssignedJobs")
                        .HasForeignKey("CustomersCustomerId");

                    b.HasOne("S3FinalV2.Models.Jobs", "Jobs")
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.Jobs", null)
                        .WithMany("AssignedJobs")
                        .HasForeignKey("JobsJobId");

                    b.Navigation("Customer");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("S3FinalV2.Models.Customers", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("S3FinalV2.Models.MechanicAssignment", b =>
                {
                    b.HasOne("S3FinalV2.Models.AssignedJobs", "AssignedJob")
                        .WithMany("MechanicAssignments")
                        .HasForeignKey("AssignedJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.Mechanics", "Mechanic")
                        .WithMany("MechanicAssignments")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedJob");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("S3FinalV2.Models.Mechanics", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeekAssignment", b =>
                {
                    b.HasOne("S3FinalV2.Models.AssignedJobs", "AssignedJob")
                        .WithMany("WorkWeekAssignments")
                        .HasForeignKey("AssignedJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.WorkWeek", "WorkWeek")
                        .WithMany("WorkWeekAssignments")
                        .HasForeignKey("WorkWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedJob");

                    b.Navigation("WorkWeek");
                });

            modelBuilder.Entity("S3FinalV2.Models.AssignedJobs", b =>
                {
                    b.Navigation("MechanicAssignments");

                    b.Navigation("WorkWeekAssignments");
                });

            modelBuilder.Entity("S3FinalV2.Models.Customers", b =>
                {
                    b.Navigation("AssignedJobs");
                });

            modelBuilder.Entity("S3FinalV2.Models.Jobs", b =>
                {
                    b.Navigation("AssignedJobs");
                });

            modelBuilder.Entity("S3FinalV2.Models.Mechanics", b =>
                {
                    b.Navigation("MechanicAssignments");
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeek", b =>
                {
                    b.Navigation("WorkWeekAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
