// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S3FinalV2.Data;

#nullable disable

namespace S3FinalV2.Migrations
{
    [DbContext(typeof(MechTrackDbContext))]
    partial class MechTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("S3FinalV2.Models.AssignedJobs", b =>
                {
                    b.Property<int>("AssignedJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedJobId"));

                    b.Property<float?>("ActualCompTime")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobsId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignedJobId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobsId");

                    b.ToTable("AssignedJobs");
                });

            modelBuilder.Entity("S3FinalV2.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("S3FinalV2.Models.Jobs", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<float>("AvgCompletionTime")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EstCompTime")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            AvgCompletionTime = 0f,
                            Description = "Change oil and oil filter",
                            EstCompTime = 0f,
                            Name = "Oil Change",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 2,
                            AvgCompletionTime = 0f,
                            Description = "Replace Break Pads",
                            EstCompTime = 0f,
                            Name = "Breaks",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 3,
                            AvgCompletionTime = 0f,
                            Description = "Replace Air Filter",
                            EstCompTime = 0f,
                            Name = "Air Filter",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 4,
                            AvgCompletionTime = 0f,
                            Description = "Replace Cabin Filter",
                            EstCompTime = 0f,
                            Name = "Cabin Filter",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 5,
                            AvgCompletionTime = 0f,
                            Description = "Balance And Install/Mount New Tires",
                            EstCompTime = 0f,
                            Name = "Tire Mounting And Balancing",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 6,
                            AvgCompletionTime = 0f,
                            Description = "Replace Windshield Wipers",
                            EstCompTime = 0f,
                            Name = "Windshield Wipers",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 7,
                            AvgCompletionTime = 0f,
                            Description = "Rotate Tires",
                            EstCompTime = 0f,
                            Name = "Tire Rotation",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 8,
                            AvgCompletionTime = 0f,
                            Description = "Remove/Drain And Replace Vehicle's Fluids",
                            EstCompTime = 0f,
                            Name = "Change Fluids",
                            Priority = "Low",
                            SkillLevel = 1
                        },
                        new
                        {
                            JobId = 9,
                            AvgCompletionTime = 0f,
                            Description = "Replace Catalitic Convertor",
                            EstCompTime = 0f,
                            Name = "Catalitic Convertor",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 10,
                            AvgCompletionTime = 0f,
                            Description = "Replace Of Spark Plugs",
                            EstCompTime = 0f,
                            Name = "Spark Plugs",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 11,
                            AvgCompletionTime = 0f,
                            Description = "Replace Head Gasket",
                            EstCompTime = 0f,
                            Name = "Internal Engine Work",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 12,
                            AvgCompletionTime = 0f,
                            Description = "Replace Water Pump",
                            EstCompTime = 0f,
                            Name = "Water Pump",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 13,
                            AvgCompletionTime = 0f,
                            Description = "Replace Alternator",
                            EstCompTime = 0f,
                            Name = "Alternator",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 14,
                            AvgCompletionTime = 0f,
                            Description = "Replace Intake",
                            EstCompTime = 0f,
                            Name = "Intake",
                            Priority = "Low  ",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 15,
                            AvgCompletionTime = 0f,
                            Description = "Replace Exhaust Manifold",
                            EstCompTime = 0f,
                            Name = "Exhaust Manifold",
                            Priority = "Low",
                            SkillLevel = 2
                        },
                        new
                        {
                            JobId = 16,
                            AvgCompletionTime = 0f,
                            Description = "Replace Clutch",
                            EstCompTime = 0f,
                            Name = "Clutch",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 17,
                            AvgCompletionTime = 0f,
                            Description = "Replace Transmission",
                            EstCompTime = 0f,
                            Name = "Transmission",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 18,
                            AvgCompletionTime = 0f,
                            Description = "Fix Electrical Issues",
                            EstCompTime = 0f,
                            Name = "Electrical Issues",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 19,
                            AvgCompletionTime = 0f,
                            Description = "Replace Pistons And Rings",
                            EstCompTime = 0f,
                            Name = "Engine Internals",
                            Priority = "Low",
                            SkillLevel = 3
                        },
                        new
                        {
                            JobId = 20,
                            AvgCompletionTime = 0f,
                            Description = "Replace Engine",
                            EstCompTime = 0f,
                            Name = "Engine Replacement",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 21,
                            AvgCompletionTime = 0f,
                            Description = "Fix Wiring",
                            EstCompTime = 0f,
                            Name = "Fix Wiring",
                            Priority = "Low",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 22,
                            AvgCompletionTime = 0f,
                            Description = "Any Work Here",
                            EstCompTime = 0f,
                            Name = "Work On A Maserati",
                            SkillLevel = 4
                        },
                        new
                        {
                            JobId = 23,
                            AvgCompletionTime = 0f,
                            Description = "Any Work Here",
                            EstCompTime = 0f,
                            Name = "Work On A Alpha Romeo",
                            SkillLevel = 4
                        });
                });

            modelBuilder.Entity("S3FinalV2.Models.MechanicAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<float>("TimeAssigned")
                        .HasColumnType("real");

                    b.Property<float>("TimeCompleted")
                        .HasColumnType("real");

                    b.HasKey("AssignmentId");

                    b.HasIndex("JobId");

                    b.HasIndex("MechanicId");

                    b.ToTable("MechanicAssignments");
                });

            modelBuilder.Entity("S3FinalV2.Models.Mechanics", b =>
                {
                    b.Property<int>("MechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicId"));

                    b.PrimitiveCollection<string>("AssignedJobs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CompletedJobs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("WeeklyHourLimit")
                        .HasColumnType("real");

                    b.HasKey("MechanicId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Mechanics");

                    b.HasData(
                        new
                        {
                            MechanicId = 1,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Ashtin Gebert",
                            SkillLevel = 4,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 2,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Patrick Rodgers",
                            SkillLevel = 4,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 3,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Aaron Barkley",
                            SkillLevel = 4,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 4,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Bird Ball",
                            SkillLevel = 3,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 5,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Kareem Ryan",
                            SkillLevel = 3,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 6,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Gabriel Wilt",
                            SkillLevel = 3,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 7,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Kelce Baker",
                            SkillLevel = 3,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 8,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Stephinie John",
                            SkillLevel = 2,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 9,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Beatriz Kareem",
                            SkillLevel = 2,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 10,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Bill Patrick",
                            SkillLevel = 2,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 11,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Ashtin Peterson",
                            SkillLevel = 2,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 12,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Eric Newton",
                            SkillLevel = 2,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 13,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Hanna Tyson",
                            SkillLevel = 1,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 14,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Diya John",
                            SkillLevel = 1,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 15,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Wilt Rodgers",
                            SkillLevel = 1,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 16,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "LeBron Ali",
                            SkillLevel = 1,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 17,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Fatima Ball",
                            SkillLevel = 1,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        },
                        new
                        {
                            MechanicId = 18,
                            AssignedJobs = "[]",
                            CompletedJobs = "[]",
                            Name = "Aaron Magic",
                            SkillLevel = 1,
                            TotalHours = 0f,
                            WeeklyHourLimit = 0f
                        });
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeek", b =>
                {
                    b.Property<int>("WorkWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkWeekId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkWeekId");

                    b.ToTable("WorkWeeks");
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeekAssignment", b =>
                {
                    b.Property<int>("WorkWeekAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkWeekAssignmentId"));

                    b.Property<int>("AssignedJobsId")
                        .HasColumnType("int");

                    b.Property<int>("WorkWeekId")
                        .HasColumnType("int");

                    b.HasKey("WorkWeekAssignmentId");

                    b.HasIndex("AssignedJobsId");

                    b.HasIndex("WorkWeekId");

                    b.ToTable("WorkWeekAssignments");
                });

            modelBuilder.Entity("S3FinalV2.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S3FinalV2.Models.AssignedJobs", b =>
                {
                    b.HasOne("S3FinalV2.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.Jobs", "Jobs")
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("S3FinalV2.Models.Customers", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("S3FinalV2.Models.Customers", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("S3FinalV2.Models.MechanicAssignment", b =>
                {
                    b.HasOne("S3FinalV2.Models.AssignedJobs", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.Mechanics", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("S3FinalV2.Models.Mechanics", b =>
                {
                    b.HasOne("S3FinalV2.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("S3FinalV2.Models.Mechanics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("S3FinalV2.Models.WorkWeekAssignment", b =>
                {
                    b.HasOne("S3FinalV2.Models.AssignedJobs", "AssignedJobs")
                        .WithMany()
                        .HasForeignKey("AssignedJobsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("S3FinalV2.Models.WorkWeek", "WorkWeek")
                        .WithMany()
                        .HasForeignKey("WorkWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedJobs");

                    b.Navigation("WorkWeek");
                });
#pragma warning restore 612, 618
        }
    }
}
