// <auto-generated />
using ADW1115HOT2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADW1115HOT2.Migrations
{
    [DbContext(typeof(SalesOrdersContext))]
    partial class SalesOrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADW1115HOT2.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Wheels"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Frames"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Handlebars"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Saddles"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Brakes"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Drivetrains"
                        });
                });

            modelBuilder.Entity("ADW1115HOT2.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            ProductDescLong = "The AeroFlo ATB wheels are designed for rugged trails with lightweight aluminum construction.",
                            ProductDescShort = "Durable mountain bike wheels",
                            ProductImage = "aeroflo-atb.jpg",
                            ProductName = "AeroFlo ATB Wheels",
                            ProductPrice = 250.00m,
                            ProductQty = 10
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            ProductDescLong = "TrailBlazer provides strength and comfort for cross-country adventures.",
                            ProductDescShort = "Lightweight alloy frame",
                            ProductImage = "trailblazer-frame.jpg",
                            ProductName = "TrailBlazer Frame",
                            ProductPrice = 500.00m,
                            ProductQty = 5
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 3,
                            ProductDescLong = "Designed for maximum grip and aerodynamic performance on road bikes.",
                            ProductDescShort = "Ergonomic racing handlebars",
                            ProductImage = "ergopro-handlebars.jpg",
                            ProductName = "ErgoPro Handlebars",
                            ProductPrice = 120.00m,
                            ProductQty = 15
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 4,
                            ProductDescLong = "ComfortRide saddles provide lasting comfort for long-distance riders.",
                            ProductDescShort = "High-density foam saddle",
                            ProductImage = "comfortride-saddle.jpg",
                            ProductName = "ComfortRide Saddle",
                            ProductPrice = 75.00m,
                            ProductQty = 20
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 5,
                            ProductDescLong = "Reliable stopping power for road and mountain bikes with easy adjustment features.",
                            ProductDescShort = "High-performance brake system",
                            ProductImage = "prostop-brakes.jpg",
                            ProductName = "ProStop Brakes",
                            ProductPrice = 90.00m,
                            ProductQty = 12
                        });
                });

            modelBuilder.Entity("ADW1115HOT2.Models.Product", b =>
                {
                    b.HasOne("ADW1115HOT2.Models.Category", "Category")
                        .WithOne("Product")
                        .HasForeignKey("ADW1115HOT2.Models.Product", "CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ADW1115HOT2.Models.Category", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
